<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        if (\DB::table('currencies')->count() > 0) {
            return;
        }

        \DB::table('currencies')->insert([
            ['code' => 'AFN', 'name' => 'Afghani', 'symbol' => '؋', 'name_ar' => 'افغاني'],
            ['code' => 'ALL', 'name' => 'Lek', 'symbol' => 'Lek', 'name_ar' => 'ليك ألباني'],
            ['code' => 'ANG', 'name' => 'Netherlands Antillian Guilder', 'symbol' => 'ƒ', 'name_ar' => 'جيلدر الأنتيل الهولندية'],
            ['code' => 'ARS', 'name' => 'Argentine Peso', 'symbol' => '$', 'name_ar' => 'بيزو أرجنتيني'],
            ['code' => 'AUD', 'name' => 'Australian Dollar', 'symbol' => '$', 'name_ar' => 'دولار أسترالي'],
            ['code' => 'AWG', 'name' => 'Aruban Guilder', 'symbol' => 'ƒ', 'name_ar' => '"فلورن أروبي'],
            ['code' => 'AZN', 'name' => 'Azerbaijanian Manat', 'symbol' => 'ман', 'name_ar' => 'مانات أذربيجاني'],
            ['code' => 'BAM', 'name' => 'Convertible Marks', 'symbol' => 'KM', 'name_ar' => 'المارك البوسني والهرسكي'],
            ['code' => 'BDT', 'name' => 'Bangladeshi Taka', 'symbol' => '৳', 'name_ar' => 'تاكا بنجلاديشي'],
            ['code' => 'BBD', 'name' => 'Barbados Dollar', 'symbol' => '$', 'name_ar' => 'دولار بربادوسي'],
            ['code' => 'BGN', 'name' => 'Bulgarian Lev', 'symbol' => 'лв', 'name_ar' => 'ليف بلغاري'],
            ['code' => 'BMD', 'name' => 'Bermudian Dollar', 'symbol' => '$', 'name_ar' => 'دولار برمودي'],
            ['code' => 'BND', 'name' => 'Brunei Dollar', 'symbol' => '$', 'name_ar' => 'دولار بروناي'],
            ['code' => 'BOB', 'name' => 'BOV Boliviano Mvdol', 'symbol' => '$b', 'name_ar' => 'ربوليفيانو بوليفي'],
            ['code' => 'BRL', 'name' => 'Brazilian Real', 'symbol' => 'R$', 'name_ar' => 'ريال برازيلي'],
            ['code' => 'BSD', 'name' => 'Bahamian Dollar', 'symbol' => '$', 'name_ar' => 'دولار باهامي'],
            ['code' => 'BWP', 'name' => 'Pula', 'symbol' => 'P', 'name_ar' => 'بولا بوتسواني'],
            ['code' => 'BYR', 'name' => 'Belarussian Ruble', 'symbol' => '₽', 'name_ar' => 'روبل بيلاروسي'],

            ['code' => 'BZD', 'name' => 'Belize Dollar', 'symbol' => 'BZ$', 'name_ar' => ' دولار بليزي'],
            ['code' => 'CAD', 'name' => 'Canadian Dollar', 'symbol' => '$', 'name_ar' => 'دولار كندي'],
            ['code' => 'CHF', 'name' => 'Swiss Franc', 'symbol' => 'CHF', 'name_ar' => 'فرنك سويسري'],
            ['code' => 'CLP', 'name' => 'CLF Chilean Peso Unidades de fomento', 'symbol' => '$', 'name_ar' => 'بيزو تشيلي'],
            ['code' => 'CNY', 'name' => 'Yuan Renminbi', 'symbol' => '¥', 'name_ar' => 'يوان صيني'],
            ['code' => 'COP', 'name' => 'COU Colombian Peso Unidad de Valor Real', 'symbol' => '$', 'name_ar' => 'بيزو كولومبي'],
            ['code' => 'CRC', 'name' => 'Costa Rican Colon', 'symbol' => '₡', 'name_ar' => 'كولون كوستاريكي'],
            ['code' => 'CUP', 'name' => 'CUC Cuban Peso Peso Convertible', 'symbol' => '₱', 'name_ar' => 'بيزو كوبي'],
            ['code' => 'CZK', 'name' => 'Czech Koruna', 'symbol' => 'Kč', 'name_ar' => 'كورونا تشيكية'],
            ['code' => 'DKK', 'name' => 'Danish Krone', 'symbol' => 'kr', 'name_ar' => 'كرونة دنماركية'],
            ['code' => 'DOP', 'name' => 'Dominican Peso', 'symbol' => 'RD$', 'name_ar' => 'بيزو دومنيكاني'],
            ['code' => 'EGP', 'name' => 'Egyptian Pound', 'symbol' => '£', 'name_ar' => 'جنيه مصري'],
            ['code' => 'EUR', 'name' => 'Euro', 'symbol' => '€', 'name_ar' => 'يورو'],
            ['code' => 'FJD', 'name' => 'Fiji Dollar', 'symbol' => '$', 'name_ar' => 'دولار فيجي'],
            ['code' => 'FKP', 'name' => 'Falkland Islands Pound', 'symbol' => '£', 'name_ar' => 'جنيه جزر فوكلاند'],
            ['code' => 'GBP', 'name' => 'Pound Sterling', 'symbol' => '£', 'name_ar' => 'جنيه إسترليني'],
            ['code' => 'GIP', 'name' => 'Gibraltar Pound', 'symbol' => '£', 'name_ar' => 'جنيه جبل طارق'],
            ['code' => 'GTQ', 'name' => 'Quetzal', 'symbol' => 'Q', 'name_ar' => 'كوتزال جواتيمالا'],
            ['code' => 'GYD', 'name' => 'Guyana Dollar', 'symbol' => '$', 'name_ar' => ' دولار غيانا'],
            ['code' => 'HKD', 'name' => 'Hong Kong Dollar', 'symbol' => '$', 'name_ar' => 'دولار هونغ كونغ'],
            ['code' => 'HNL', 'name' => 'Lempira', 'symbol' => 'L', 'name_ar' => 'ليمبيرا هندوراس'],
            ['code' => 'HRK', 'name' => 'Croatian Kuna', 'symbol' => 'kn', 'name_ar' => 'كونا كرواتي'],
            ['code' => 'HUF', 'name' => 'Forint', 'symbol' => 'Ft', 'name_ar' => 'فورينت مجري'],
            ['code' => 'IDR', 'name' => 'Rupiah', 'symbol' => 'Rp', 'name_ar' => 'روبية إندونيسية'],
            ['code' => 'ILS', 'name' => 'New Israeli Sheqel', 'symbol' => '₪', 'name_ar' => 'شيكل'],
            ['code' => 'IRR', 'name' => 'Iranian Rial', 'symbol' => '﷼', 'name_ar' => 'ريال إيراني'],
            ['code' => 'ISK', 'name' => 'Iceland Krona', 'symbol' => 'kr', 'name_ar' => 'كرونا أيسلندية'],
            ['code' => 'JMD', 'name' => 'Jamaican Dollar', 'symbol' => 'J$', 'name_ar' => 'دولار جامايكي'],
            ['code' => 'JPY', 'name' => 'Yen', 'symbol' => '¥', 'name_ar' => 'ين ياباني'],
            ['code' => 'KGS', 'name' => 'Som', 'symbol' => 'лв', 'name_ar' => 'سوم قيرغيزستاني'],
            ['code' => 'KHR', 'name' => 'Riel', 'symbol' => '៛', 'name_ar' => 'رييل كمبودي'],
            ['code' => 'KPW', 'name' => 'North Korean Won', 'symbol' => '₩', 'name_ar' => 'وون كوريا الشمالية'],
            ['code' => 'KRW', 'name' => 'Won', 'symbol' => '₩', 'name_ar' => 'وون كوريا الجنوبية'],
            ['code' => 'KYD', 'name' => 'Cayman Islands Dollar', 'symbol' => '$', 'name_ar' => 'دولار جزر كايمان'],
            ['code' => 'KZT', 'name' => 'Tenge', 'symbol' => 'лв', 'name_ar' => 'تينغ كازاخستاني'],
            ['code' => 'LAK', 'name' => 'Kip', 'symbol' => '₭', 'name_ar' => ' كيب لاوسي'],
            ['code' => 'LBP', 'name' => 'Lebanese Pound', 'symbol' => '£', 'name_ar' => 'ليرة لبنانية'],
            ['code' => 'LKR', 'name' => 'Sri Lanka Rupee', 'symbol' => '₨', 'name_ar' => 'روبية سريلانكية'],
            ['code' => 'LRD', 'name' => 'Liberian Dollar', 'symbol' => '$', 'name_ar' => 'دولار ليبيري'],
            ['code' => 'LTL', 'name' => 'Lithuanian Litas', 'symbol' => 'Lt', 'name_ar' => 'يتا ليتوانية'],
            ['code' => 'LVL', 'name' => 'Latvian Lats', 'symbol' => 'Ls', 'name_ar' => ' لاتس لاتفيا'],
            ['code' => 'MKD', 'name' => 'Denar', 'symbol' => 'ден', 'name_ar' => 'دينار مقدوني'],
            ['code' => 'MNT', 'name' => 'Tugrik', 'symbol' => '₮', 'name_ar' => 'توغروغ منغولي'],
            ['code' => 'MUR', 'name' => 'Mauritius Rupee', 'symbol' => '₨', 'name_ar' => 'روبية موريشيوسية'],
            ['code' => 'MXN', 'name' => 'MXV Mexican Peso Mexican Unidad de Inversion (UDI]', 'symbol' => '$', 'name_ar' => 'بيزو مكسيكي'],
            ['code' => 'MYR', 'name' => 'Malaysian Ringgit', 'symbol' => 'RM', 'name_ar' => 'رينغيت ماليزي'],
            ['code' => 'MZN', 'name' => 'Metical', 'symbol' => 'MT', 'name_ar' => 'متكال موزمبيقي'],
            ['code' => 'NGN', 'name' => 'Naira', 'symbol' => '₦', 'name_ar' => 'نايرا نيجيري'],
            ['code' => 'NIO', 'name' => 'Cordoba Oro', 'symbol' => 'C$', 'name_ar' => ' كوردوبة نيكاراغوا'],
            ['code' => 'NOK', 'name' => 'Norwegian Krone', 'symbol' => 'kr', 'name_ar' => 'كرونة نرويجية'],
            ['code' => 'NPR', 'name' => 'Nepalese Rupee', 'symbol' => '₨', 'name_ar' => ' روبية نيبالية'],
            ['code' => 'NZD', 'name' => 'New Zealand Dollar', 'symbol' => '$', 'name_ar' => 'دولار نيوزيلندي'],
            ['code' => 'OMR', 'name' => 'Rial Omani', 'symbol' => '﷼', 'name_ar' => ' ريال عماني'],
            ['code' => 'PAB', 'name' => 'USD Balboa US Dollar', 'symbol' => 'B/.', 'name_ar' => 'بالبوا بنمي'],
            ['code' => 'PEN', 'name' => 'Nuevo Sol', 'symbol' => 'S/.', 'name_ar' => 'سول بيروفي'],
            ['code' => 'PHP', 'name' => 'Philippine Peso', 'symbol' => 'Php', 'name_ar' => ' بيزو فلبيني'],
            ['code' => 'PKR', 'name' => 'Pakistan Rupee', 'symbol' => '₨', 'name_ar' => 'روبية باكستانية'],
            ['code' => 'PLN', 'name' => 'Zloty', 'symbol' => 'zł', 'name_ar' => 'زلوتي بولندي'],
            ['code' => 'PYG', 'name' => 'Guarani', 'symbol' => 'Gs', 'name_ar' => 'جواراني باراغواي'],
            ['code' => 'QAR', 'name' => 'Qatari Rial', 'symbol' => '﷼', 'name_ar' => 'ريال قطري'],
            ['code' => 'RON', 'name' => 'New Leu', 'symbol' => 'lei', 'name_ar' => 'ليو روماني'],
            ['code' => 'RSD', 'name' => 'Serbian Dinar', 'symbol' => 'Дин.', 'name_ar' => 'دينار صربي'],
            ['code' => 'RUB', 'name' => 'Russian Ruble', 'symbol' => 'руб', 'name_ar' => 'روبل روسي'],
            ['code' => 'SAR', 'name' => 'Saudi Riyal', 'symbol' => '﷼', 'name_ar' => 'ريال سعودي'],
            ['code' => 'SBD', 'name' => 'Solomon Islands Dollar', 'symbol' => '$', 'name_ar' => 'دولار جزر سليمان'],
            ['code' => 'SCR', 'name' => 'Seychelles Rupee', 'symbol' => '₨', 'name_ar' => 'روبية سيشيلية'],
            ['code' => 'SEK', 'name' => 'Swedish Krona', 'symbol' => 'kr', 'name_ar' => ' كرونا سويدية'],
            ['code' => 'SGD', 'name' => 'Singapore Dollar', 'symbol' => '$', 'name_ar' => 'دولار سنغافوري'],
            ['code' => 'SHP', 'name' => 'Saint Helena Pound', 'symbol' => '£', 'name_ar' => 'جنيه سانت هيليني'],
            ['code' => 'SOS', 'name' => 'Somali Shilling', 'symbol' => 'S', 'name_ar' => ' شلن صومالي'],
            ['code' => 'SRD', 'name' => 'Surinam Dollar', 'symbol' => '$', 'name_ar' => 'دولار سورينامي'],
            ['code' => 'SVC', 'name' => 'USD El Salvador Colon US Dollar', 'symbol' => '$', 'name_ar' => 'كولون إل سلفادوري'],
            ['code' => 'SYP', 'name' => 'Syrian Pound', 'symbol' => '£', 'name_ar' => 'ليرة سورية'],
            ['code' => 'THB', 'name' => 'Baht', 'symbol' => '฿', 'name_ar' => 'باهت تايلاندي'],
            ['code' => 'TRY', 'name' => 'Turkish Lira', 'symbol' => 'TL', 'name_ar' => 'ليرة تركية'],
            ['code' => 'TTD', 'name' => 'Trinidad and Tobago Dollar', 'symbol' => 'TT$', 'name_ar' => 'دولار ترينيداد وتوباغو'],
            ['code' => 'TWD', 'name' => 'New Taiwan Dollar', 'symbol' => 'NT$', 'name_ar' => 'دولار تايواني'],
            ['code' => 'UAH', 'name' => 'Hryvnia', 'symbol' => '₴', 'name_ar' => 'هريفنيا أوكرانية'],
            ['code' => 'USD', 'name' => 'US Dollar', 'symbol' => '$', 'name_ar' => 'دولار أمريكي'],
            ['code' => 'UYU', 'name' => 'UYI Uruguay Peso en Unidades Indexadas', 'symbol' => '$U', 'name_ar' => 'بيزو أوروغواي'],
            ['code' => 'UZS', 'name' => 'Uzbekistan Sum', 'symbol' => 'лв', 'name_ar' => 'سوم أوزبكستاني'],
            ['code' => 'VEF', 'name' => 'Bolivar Fuerte', 'symbol' => 'Bs', 'name_ar' => 'بوليفار فنزويلي'],
            ['code' => 'VND', 'name' => 'Dong', 'symbol' => '₫', 'name_ar' => ' دونج فيتنامي'],
            ['code' => 'XCD', 'name' => 'East Caribbean Dollar', 'symbol' => '$', 'name_ar' => 'دولار شرق الكاريبي'],
            ['code' => 'YER', 'name' => 'Yemeni Rial', 'symbol' => '﷼', 'name_ar' => 'ريال يمني'],
            ['code' => 'ZAR', 'name' => 'Rand', 'symbol' => 'R', 'name_ar' => 'راند جنوب إفريقيا'],
        ]);
    }
}
